config/access-cm2.yaml, config/access-esm1-5.yaml, shell/build_all.sh, src/catalog_manager/__init__.py, src/catalog_manager/esmcat/builders.py, src/catalog_manager/esmcat/utils.py
OM2, ESM1.5 and CM2 Builders now apply `"join_new" aggregation` across "member" attribute that is parsed from the experiment id. This can be used to concatenate multiple ensemble members into a single experiment.
Closes #24
=> Support ensemble concatenation across experiments

bin/build_all.sh, config/access-cm2.yaml, environment.yaml, src/access_nri_intake/esmcat/builders.py, src/access_nri_intake/esmcat/utils.py
Here we revert back to using xarray in the esm parsers and include as variables only `data_vars`.
Closes #63
=> Only add `data_vars` to esm catalogs

bin/build_all.sh, src/access_nri_intake/cat/catalog.yaml
New build of the catalog to `xp65` for use in MED-managed environment
=> Release v0.0.6

docs/usage/chunking.ipynb, docs/usage/quickstart.ipynb, pyproject.toml
I noticed a couple of minor typos in the hint for how to use the dask dashboard. These are fixed here
=> Fix small typos in tutorials

.github/workflows/cd.yml
This PR changes the PyPI publish workflow to use OpenID Connect over a repo secret.
=> Move to trusted publishing

.conda/meta.yaml, ci/environment-3.10.yml, ci/environment-3.11.yml, ci/environment-3.9.yml, pyproject.toml, src/access_nri_intake/source/builders.py
This PR updates dependencies to versions compatible with pydantic v2. Note the new dependency versions haven't actually been released yet, but they should be released this month so for now I've just put placeholders for version numbers (this is why the checks are failing).
Closes #101, Closes #102
=> Update for pydantic v2 compatibility

config/access-om2.yaml
This PR adds the 45 1deg_jra55_iaf_omip2_cycles - see https://forum.access-hive.org.au/t/access-om2-control-runs/258
Closes #105
=> Add COSIMA 1deg_jra55_iaf_omip2spunup_cycles

src/access_nri_intake/source/utils.py, tests/test_source_utils.py
This PR implements changes to `source.utils.get_timeinfo` to allow it to return `subhr` frequencies.
Closes #110
=> Allow `get_timeinfo` to return `subhr` frequencies

src/access_nri_intake/source/utils.py, tests/test_source_utils.py
With this PR, when no time bounds are available in a file, a guess of the start and end dates are made based on the first and last time and the frequency.
@aidanheerdegen, @utkarshgupta95 this is definitely a yucky hack, but it should fix #113 and #114.
Closes #113, closes #114
=> Guess start and end date when no time bounds are available

config/access-om2.yaml, src/access_nri_intake/source/utils.py, tests/test_source_utils.py
The COSIMA experiment `01deg_jra55v140_iaf_cycle3` output is split across multiple project directories. There is some data at each of these locations:
- `/g/data/ik11/outputs/access-om2-01/01deg_jra55v140_iaf_cycle3` (25T)
- `/g/data/cj50/access-om2/raw-output/access-om2-01/01deg_jra55v140_iaf_cycle3` (24T)
This PR adds the `ik11` data which were previously missing
Closes #122
=> Add other half of `01deg_jra55v140_iaf_cycle3`

.readthedocs.yml, src/access_nri_intake/catalog/manager.py, src/access_nri_intake/cli.py, tests/test_manager.py
The `CatalogManager` class is clunky and has some out-of-date docstrings. This PR reorganises the class a little to try and make it clearer and capable of loading different types of intake data source. Main changes:
- the `add` method is no longer public. Entries are added to the catalog at the end of the `build_esm` or `load` methods.
- saving the catalog is now its own method
- the `load` method now supports a `driver` argument for loading different types of intake data source
Closes #128
=> Tidy up CatalogManager API

bin/create_metadata_yaml_template.py, bin/validate_metadata_yaml.py, metadata.yaml, src/access_nri_intake/catalog/__init__.py
Use latest version of experiment schema, which allows `version` to be a string (not just a number)
=> Update schema to allow version strings

docs/usage/chunking.ipynb
With xarray >= v2023.09.0 the behaviour of `xarray.open_dataset(..., chunks={})` has changed. This chunking strategy is used by default by Intake-ESM. The PR updates the chunking quickstart tutorial in the documentation to include information about this change.
Closes #126
=> Update chunking quickstart for recent xarray chunking changes

config/access-om2.yaml
Adds the runs described in this ACCESS-Hive Forum post to the catalog: https://forum.access-hive.org.au/t/era-5-forced-access-om2-simulations/1103
Closes #127
=> Add ERA5-forced ACCESS-OM2 runs

.github/workflows/gadi_deploy.yml
Hi @dougiesquire 
This is a draft but I am gonna have to push that to `main` so I can test the workflow...
GitHub does not have the option to run actions from anything else than the main branch.
Is that OK with you?
=> Draft action for automated update of the catalog on Gadi

.conda/meta.yaml, ci/environment-3.10.yml, ci/environment-3.11.yml, ci/environment-3.9.yml, pyproject.toml
Pin intake at 0.7.0 to avoid alpha intake v2. See #153 for context.
=> Pin intake=0.7.0

src/access_nri_intake/source/builders.py, tests/test_builders.py
"wave" is [now](https://github.com/ACCESS-NRI/access-nri-intake-catalog/pull/161) an acceptable realm in the schema. This PR assigns WW3 data to the wave realm in the `AccessOm3Builder`
=> Assign ww3 data to wave realm in access-om3 builder

.conda/meta.yaml, ci/environment-3.10.yml, ci/environment-3.11.yml, ci/environment-3.9.yml, docs/conf.py, pyproject.toml, src/access_nri_intake/source/builders.py, tests/test_builders.py
Very simple PR to remove use of the deprecated `applymap` method. Closes #172
ADDED: Also includes a workaround for a new issue in sphinx-autoapi
=> Replace deprecated pandas `applymap` with `map`

docs/management/catalog.rst, docs/management/source.rst
Reading the doc and came across that link that seems old.
=> Update path to schema

docs/usage/how.rst
Using `conda/are` within the xp65 project allows the user to import the intake catalog in ARE, whereas `conda/access-med` no longer works.  To reflect this change, `conda/are` has been replaced with `conda/access-med` in the 'How do I use it?' section of the docs. 
Fixes issue #182
=> Update xp65 environment

pyproject.toml, src/access_nri_intake/catalog/__init__.py, src/access_nri_intake/cli.py, src/access_nri_intake/data/__init__.py, src/access_nri_intake/data/metadata_schema_experiment.json, src/access_nri_intake/data/metadata_schema_file.json, src/access_nri_intake/source/__init__.py, src/access_nri_intake/utils.py, tests/test_data.py, tests/test_utils.py
This PR closes #185 by incorporating the schema descriptions (JSON) into the package. This has been done IAW what I think is current best practice for storing & loading data files within a package (https://docs.python.org/3/library/importlib.resources.html#module-importlib.resources).
Whilst doing this, I found a couple of places where the `data` submodule was doing some ad-hoc local data loads. These have also been updated to use the new pattern.
Open questions:
- Is this how we want to ship schema? How often do the schema need updating, and is it a pain to have to tag a new version every time an update is required?
=> 185 ship schema with package

config/cmip5.yaml, config/cmip6.yaml, config/experiments/cmip5-al33/metadata.yaml, config/experiments/cmip5-rr3/metadata.yaml, config/experiments/cmip6-fs38/metadata.yaml, config/experiments/cmip6-oi10/metadata.yaml
Closes #200 .
New `metadata.yaml` have been placed in `/g/data/xp65/admin/intake/metadata/`, and referenced in the catalog `config` YAMLs.
=> Update metadata locations for existing CMIP5 and CMIP6 experiments

.github/workflows/ci.yml, pyproject.toml, tests/test_cli.py, tests/test_data.py
- Fixed issue where `tests/test_data::test_get_catalog_fp()` would only work when performed using an editable installation.
Closes #226
=> 226 editable install

pyproject.toml, tox.ini
This branch contains expanded testing to ensure a smooth update to intake take2. 
It won't exactly close #153, as it doesn't pin the intake version to >=2.0.0, but it:
- Relaxed intake version in `pyproject.toml` to allow for versions greater than 0.7.0, reverting #154.
- Adds tox environments for dependency configurations which test this package against the various configurations of intake (0.7.0, 2.0.7) & intake esm (no coordinates, coordinates).
There are no indications from any test environments/configurations that intake take2 causes any issues: all tests are passing, with:
-  xfail for `test_builders.py::test_parse_access_ncfile[AccessOm2Builder-access-om2/output000/ocean/ocean_grid.nc-expected0-True]` when coordinate variable discovery is not enabled in intake-esm
- All tests …
=> Intake Take2

src/access_nri_intake/cli.py, tests/data/catalog/catalog-orig.yaml, tests/test_cli.py
Fixes #246 .
This PR handles the case where a new-style catalog (vYYYY-MM-DD) is built, but an old-style catalog (vX.X.X) is present in the catalog build directory.
The code will now treat this the same as a no-catalog-exists case (new `catalog.yaml`, set min and max version based on the catalog directories present), with the exception that the storage flags from the old-style catalog will be merged in.
=> Handle case of creating new-style catalog when old-style catalog already exists

src/access_nri_intake/catalog/manager.py, src/access_nri_intake/catalog/translators.py, src/access_nri_intake/catalog/utils.py, tests/test_manager.py
- I fixed up a couple of tangentially related bits in the translators - looks like some WIP got accidentally merged in the @tuplify_series decorator & moved that to a separate file.
- Added more thorough error handling, checking for specific data issues & pointing to #223 is it appears to be related.
- Tests for error handling. 
- The tests use mock raises - I'd really rather avoid this if possible & pass data broken in the specific expected ways, but it was sinking too much time so I'll raise it as a new issue & come back to check.
=> 223-model-required

src/access_nri_intake/cli.py, tests/test_cli.py
Fixes #263 .
The issue was a stray `get_catalog_fp()` call that hadn't been converted correctly to a reference to `build_base_path`.
PR also includes a test for when the `catalog.yaml` is stored separately to the data directories, and where existing 'version directories' are in the *catalog* directory (these shouldn't be found/considered).
=> Fix bug in location used to check for existing catalogs

CHANGELOG.rst
Moves us towards v1.0.0 release (#277 ).
I can't find anywhere else that the version needs to be updating - I'm presuming the `versioneer`/GitHub actions handle that.
=> Changelog updates for v1.0.0

CHANGELOG.rst, bin/build_all.sh
It looks like a lot of experiments got missed in the build script when new data requests were merged in. Not sure how that happened, but this PR corrects it.
=> Add missing experiments to build script

config/metadata_sources/cordex-ig45/metadata.yaml
Fixes #283 .
There were some (very minor) metadata fixes required for the `ig45` CORDEX experiment. @charles-turner-1 is pushing these changes to the 'live' version of the metadata on `xp65`.
Note that this PR isn't strictly necessary for v1.0.0 (#230 ), but it's good to keep the repo reference copies up-to-date with the live copies.
=> Metadata fixes for ig45 cordex

config/metadata_sources/era5-rt52/metadata.yaml, config/metadata_sources/narclim2-zz63/metadata.yaml
Fixes #286.
This PR contains metadata format fixes for the experiments `era5-rt52` and `narclim2-zz63`.
@charles-turner-1 before approving the PR and merging, you'll need to copy both of the new files over to the live location on `xp65` (I found a stray comma in the narclim keywords list that I dealt with).
=> Fix metadata bugs in ERA5, Narclim

src/access_nri_intake/catalog/manager.py, src/access_nri_intake/cli.py, tests/test_cli.py, tests/test_manager.py
Closes #257, and makes some progress on #271.
Unfortunately I got mixed up and have removed a lot of the wrong mocks, but this PR currently replaces a lot of the (I think unnecessary) mocks in the `tests/test_cli.py` file, as well as replacing a lot of calls to the `os` module with `pathlib`.
Marked as draft because I still need to address the mocks in #257, but it seemed logical to bundle these all together.
@marc-white If you still remember the context of these tests, can you tell me if I'm violating any of the intentions with my changes?
=> 257 replace mocks

src/access_nri_intake/cli.py, src/access_nri_intake/experiment/utils.py, tests/test_cli.py, tests/test_experiment.py
Closes #328 .
- I also rewrote the parse_kwargs functionality to use ast.literal_eval instead of some very custom logic. Potentially this could be cleaned up further - I suspect argparse might have something in it that negates the need for it.
=> 328 datastore names

src/access_nri_intake/cli.py, tests/data/config/access-om2-bad-labels.yaml, tests/test_cli.py
(Re) closes #307 .
This PR makes a minor change - if bad experiment metadata is encountered, rather than raising an Exception, a warning is produced instead, and the experiment is not included in the resulting catalog.
=> Make catalog build robust against bad experiment metadata

.conda/meta.yaml, pyproject.toml
Related to issue in #335.
Should really have included this in v1.1.0 really - maybe v1.1.1 is coming sooner than expected.
=> Bump intake-dataframe-catalog requirement

src/access_nri_intake/catalog/manager.py, src/access_nri_intake/source/builders.py, tests/data/config/access-om2-patterns.yaml, tests/test_builders.py, tests/test_cli.py
Closes #343 .
This PR updates all existing builders in `main` to allow the builder `include_patterns` and `exclude_patterns` to be specified from the configuration YAML file on a per-experiment basis. The previously-used defaults are still in place if one/both of those values are not defined in the configuration YAML.
Tests included.
=> Set include_patterns/exclude_patterns from configuration YAMLs

src/access_nri_intake/experiment/main.py
Ran into some issues with homedirs - ie. `~/...`.
=> Add expanduser() to paths in use_datastore and hash_catalog

src/access_nri_intake/cli.py, tests/test_cli.py
Closes #358 .
This PR adds a new check step to the catalog build process. It will cause the build to fail (early) with a `RuntimeError` if the user running the build doesn't have access to one or more of the necessary project storage areas.
=> Fail build if all necessary storage can't be accessed

src/access_nri_intake/catalog/translators.py, src/access_nri_intake/catalog/utils.py, tests/test_translators.py
Around the 1.0.0 release, I added a decorator to report failing translators, but the implementation was a bit messy - wasn't preserving metadata correctly, circular import workarounds, etc.
This PR cleans that up. Low priority.
=> Translator metadata fixes

src/access_nri_intake/cli.py, tests/conftest.py, tests/test_cli.py
Closes #372 .
It turns out the stray `metadata.yaml` came from the `test_entrypoint` test. Because `metadata-template` did not originally use the `argparse` structure, calling `metadata-template --help` did nothing special - it just executed the command with no arguments, and hence wrote a `metadata.yaml` in the CWD with no teardown to remove it. (We didn't notice earlier because the later test that intentionally tested the CWD template write *does* have teardown, so was covering up the issue.)
This PR:
- Adds correct `argparse` usage to `metadata-template`, so `test_entrypoint` now works as expected;
- Updates the `metadata-template` tests to use correct `argparse` formatting;
- Added a per-function pytest fixture to raise a `UserWarning` if a `metadata.yaml` is left hanging in the CWD …
=> Update metadata-template CLI

src/access_nri_intake/source/builders.py
Noticed this was missing.
pending:
=> Add ROMSBuilder to `builders.__all__`

docs/index.rst, docs/usage/telemetry.rst
Don't think I was firing on all cylinders yesterday - just fixed a bunch of typos I created in the docs.
=> Fix docs typos

.conda/meta.yaml, pyproject.toml
Sorry - screwed up & forgot to add the deps in `.conda/meta.yaml` too. This will have broken the catalog in 25.04 & will need a new release.
Dougie sent me something that could be used to automate syncing these dependencies up, so I'll integrate that before I make the same cockup again.
=> Fix conda deps

config/access-om2.yaml
Closes #389 .
Experiment location for 01deg_jra55v13_ryf9091 updated as requested. Note that a catalog build will need to be triggered for the change to take full effect.
=> Update experiment location for 01deg_jra55v13_ryf9091

src/access_nri_intake/data/__init__.py
- Change `Except FileNotFoundError` => `Except Exception`
None - this is a hotfix.
I'm pretty sure that at some points during a catalog build, we expect to see potential `EmptyDataErrors` as our default (ie. most recent build) file exists but contains no meaningful data.
I think we'll want to break this up into more meaningful exceptions, I'll raise an issue re. that.
This further triggers a telemetry error as our error handling isn't triggered as we only account for FileNotFoundError in our ecxeption handling. 
See traceback: 
```python
---------------------------------------------------------------------------
EmptyDataError                            Traceback (most recent call last)
File [/g/data/xp65/public/apps/med_conda/envs/analysis3-25.05/lib/python3.11/site-packages/access_nri_in …
```
=> Loosen exception catch when importing catalog - errors change when a build is ongoing

src/access_nri_intake/catalog/translators.py
Updates `FREQUENCY_TRANSLATORS` to include new values for `barpa_py18` and `esgf_ref_qv56`, and adds frequency name mapping to `CordexTranslator`.
Will close #405 .
- In order to build a new catalog including this additional datastore, you will need to either release a new version of the `access-nri-intake` package, or run the `bin/build_all.sh` script to build a new catalog, using a virtual environment with the most recent (ie. including this PR) version of `access-nri-intake` installed. This can be done by activating the `venv` in `/g/data/xp65/admin/access-nri-intake-catalog/bin/build_all.sh` job.
Changes have been confirmed to work with both direct investigation via Jupyter, and by a restricted test catalog build.
=> Fix issues with frequency translations

src/access_nri_intake/source/builders.py, tests/test_builders.py
- Allow for some trailing characters in the om2 builder regex patterns.
- Test for this case.
https://github.com/COSIMA/cosima-recipes/issues/313 : Sea_Ice_Seasonality_Statistics.ipynb requires it.
=> Update Om2 Builder pattern for '01deg_jra55v140_iaf_cycle2'

src/access_nri_intake/cli.py
- Reminder to post on the forum, after a catalog build has been completed. Emitted as part of the job log.
=> Add forum post reminder

bin/build_all.sh, config/metadata_sources/mom6-panant-0025-zstar-ACCESSyr2-ol01/metadata.yaml, config/metadata_sources/mom6-panant-005-zstar-ACCESSyr2-ol01/metadata.yaml, config/metadata_sources/mom6-panant-01-zstar-ACCESSyr2-ol01/metadata.yaml, config/mom6.yaml, docs/project_list.rst, docs/storage_flags.rst
Add the `ACCESS2yr` panant experiments to the catalog.
Closes #420 .
-  [x] The new datastore has been added to the list of configs in `bin/build_all.sh` and `bin/test_end_to_end.sh`, and the storage flags in both scripts updated, if necessary.
- In order to build a new catalog including this additional datastore, you will need to either release a new version of the `access-nri-intake` package, or run the `bin/build_all.sh` script to build a new catalog, using a virtual environment with the most recent (ie. including this PR) version of `access-nri-intake` installed. This can be done by activating the `venv` in `/g/data/xp65/admin/access-nri-intake-catalog/bin/build_all.sh` job.
Test build successfully added the new experiments.
=> Add more panant experiments (MOM6)

src/access_nri_intake/catalog/translators.py, src/access_nri_intake/cli.py
- Fix translator for Barpa by adding a '20min' translation to the big `FREQUENCY_TRANSLATIONS` list
- Change translator for `EsmValToolTranslator` default to "none" - was just returning the name of frequencys that weren't found, which was realm derived & caused the issue.
- I've changed the warning in the main catalog build script - it wasn't emitting the full warning properly. This might negate the need for the pymalloctraceback stuff @marc-white ?
Closes #418
=> 418 fix barpa

src/access_nri_intake/source/builders.py, tests/test_builders.py
- Add a property to `BaseBuilder` to track the valid assets without the user having to construct it manually every time they want it.
Lays some groundwork for #344 , along with #465 .
=> Add `valid_assets` property to `BaseBuilder` class

src/access_nri_intake/cli.py
- Add some coloured highlights to the help message:
#508 
- [N/A] Unit tests for the changes exist
- [N/A] Tests pass on CI
- [ N/A] Documentation reflects the changes where applicable
=> Colours in help message
