ACCESS-NRI/access-nri-intake-catalog

- docs/conf.py
- scripts/build_all.sh
- scripts/validate_metadata_yaml.py
- src/catalog_manager/cli.py
The CLI now first checks:
- duplicated experiment names
- duplicated uuids
- metadata.yaml jsonschema
Closes #39
> Add a few checks prior to processing with CLI

- src/catalog_manager/dfcatalog.yaml
- src/catalog_manager/metacat/manager.py
The intake-dataframe-catalog API changed slightly in https://github.com/ACCESS-NRI/intake-dataframe-catalog/pull/8
This PR adds changes to work with the API change
Closes #46
> Updates for new intake-df-catalog API

- bin/build_all.sh
- config/access-cm2.yaml
- config/access-esm1-5.yaml
- config/access-om2.yaml
- config/cmip5.yaml
- config/cmip6.yaml
- config/erai.yaml
- docs/development/contrib_code.rst
- pyproject.toml
- src/access_nri_intake/__init__.py
- src/access_nri_intake/cat/__init__.py
- src/access_nri_intake/cat/metacatalog.yaml
- src/access_nri_intake/cli.py
> Version catalog files on Gadi

- pyproject.toml
- src/access_nri_intake/cat/catalog.yaml
Package data missing from v0.0.5
> Release v0.0.5.post1

- src/access_nri_intake/metacat/translators.py
- src/access_nri_intake/utils.py
> Don't convert arrays to tuples when reading metadata.yaml

- docs/usage/quickstart.ipynb
It is a very powerful data discovery tool!
> Big up the data discovery

- .conda/meta.yaml
- ci/environment-3.10.yml
- ci/environment-3.11.yml
- ci/environment-3.9.yml
- pyproject.toml
> Update Intake-ESM dependency

- .conda/meta.yaml
- ci/environment-3.10.yml
- ci/environment-3.11.yml
- ci/environment-3.9.yml
- pyproject.toml
> Require intake-dataframe-catalog>=0.2.4

- .github/workflows/gadi_deploy.yml
- bin/build_all.sh
This requires testing on the main branch.
> Update Deploy Github action

- .github/workflows/gadi_deploy.yml
- bin/build_all.sh
> Automated deployment

- tests/test_cli.py
Fixes #270 .
The `test_cli` suite previously used `tempfile.TemporaryDirectory` to create test spaces. This likely wasn't being torn down properly, so those have all been switched to use the `pytest` `tmp_path` fixture.
> Switch to correct tmp_path usage in tests

- tests/conftest.py
- tests/test_metadata_sources.py
I really like the implementation of these tests @marc-white.
Ready to merge.
> 285 add metadata validation tests

- src/access_nri_intake/catalog/translators.py
- src/access_nri_intake/catalog/utils.py
- tests/test_translators.py
- Added error handling 
- Draft for a decorator that should keep the error handling all in one place - having some issues getting the correct function name to pass through though.
> 297 translator errors

- src/access_nri_intake/cli.py
> Clarify error string

- .github/workflows/cd.yml
For more info, see [here](https://github.com/uibcdf/action-build-and-upload-conda-packages/issues/29#issuecomment-2649951251) and [here](https://github.com/ACCESS-NRI/um2nc-standalone/blob/b44e549ec1ba729ffb525bf4fc80f55fc3e72107/.github/workflows/CD.yml#L49-L63)
> Conda Deployment issues workaround

- ci/environment-3.10.yml
- ci/environment-3.11.yml
- ci/environment-3.12.yml
- ci/environment-3.13.yml
- pyproject.toml
- tests/conftest.py
> Remove xfail marker

- bin/build_all.sh
> Add missing ESGF YAML to build_all.sh

- bin/build_all.sh
- src/access_nri_intake/catalog/translators.py
Looks like we also missed altering __all__ in translators...
> 391 bug add esgf sources to build script

- bin/test_end_to_end.sh
- Update permissions for E2E tests.
> Easier to just copy main build permissions than check if they're needed

- docs/conf.py
Automate update of the copyright string.
#402
-  [ ] The new datastore has been added to the list of configs in `bin/build_all.sh` and `bin/test_end_to_end.sh`, and the storage flags in both scripts updated, if necessary.
- In order to build a new catalog including this additional datastore, you will need to either release a new version of the `access-nri-intake` package, or run the `bin/build_all.sh` script to build a new catalog, using a virtual environment with the most recent (ie. including this PR) version of `access-nri-intake` installed. This can be done by activating the `venv` in `/g/data/xp65/admin/access-nri-intake-catalog/bin/build_all.sh` job.
> Update copyright in docs, Fix #402

- .github/pull_request_template.md
- Add placeholder sections to the PR template describing the actual metadata.yaml path
Closes #388
Doesn't do any automation, but it'll stop us forgetting it.
> 388 Update PR template

- tests/e2e/test_datasets_representative.py
- tests/e2e/test_end_to_end.py
Updates to end to end tests to account for:
- Concretisation related changes (won't overwrite unless --force is specified now), but we don't need to concretise for tranlator tests anyway. 
- Datastore changes
Closes #419
> 419 Fix end to end tests

- .pre-commit-config.yaml
- docs/usage/how.rst
- src/access_nri_intake/source/builders.py
- src/access_nri_intake/source/utils.py
- tests/test_builders.py
- tests/test_source_utils.py
- Builds off #378, rebases in #450
The merge conflicts were too messy to just add the commits onto #378, so I'm opening a separate branch here so I can see whats going on
> 378: Merge in reversion to functional time parsing

- src/access_nri_intake/experiment/main.py
- tests/test_experiment.py
#464 was made against the new file_id branch - didn't realise until post merging. This PR just cherry picks out the 3 relevant commits to put them into main.
Already reviewed by @joshuatorrance on that branch.
#464
> 464- Invalid assets into main (repeat)

- ci/environment-3.10.yml
- ci/environment-3.11.yml
- ci/environment-3.12.yml
- ci/environment-3.13.yml
- pyproject.toml
- tests/test_environ.py
- Fixes polars v1.33 breaking changes, at least in theory.
> Swap to using our intake-esm fork

- .github/workflows/ci.yml
Our CI runs all the tests twice. Let's see if we can fix it.
N/A
> Does this CI change fix the running all the tests twice?

- .github/workflows/ci.yml
Tweaking changes merged in #516 with recomendation from @dougiesquire 
N/A
> Take 2: Does this CI change fix the running all the tests twice?
